# Generated by Django 5.2.4 on 2025-07-20 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_postmedia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postmedia",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_media",
                to="posts.post",
            ),
        ),
    ]
