# Generated by Django 5.2.4 on 2025-07-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_postmedia_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="save",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="share",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
