version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - ./.env
    volumes:
     - mysql:/var/lib/mysql
    ports:
      - '3307:3306'
    restart: unless-stopped
  
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '6379:6379'
    restart: unless-stopped
  
  backend:
    build:
      context: .
    image: social_media
    container_name: social_media
    command: gunicorn SocialMedia.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/src/app
      - static:/src/app/staticfiles
      - media:/src/app/media
    depends_on:
      - db
      - redis
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    restart: unless-stopped
  
  celery_worker:
    build:
      context: .
    image: social_media
    container_name: celery_worker
    command: celery -A SocialMedia worker --loglevel=INFO
    depends_on:
      - backend
      - redis
    env_file:
      - ./.env
    restart: unless-stopped
    volumes:
      - ./:/src/app
      - static:/src/app/staticfiles
      - media:/src/app/media

volumes:
  mysql:
  static:
  media: