version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - ./.env
    volumes:
     - mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    restart: unless-stopped
  
  backend:
    build:
      context: .
    image: social_media
    container_name: social_media
    volumes:
      - static:/src/app/static
      - media:/src/app/media
    depends_on:
      - db
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    restart: unless-stopped

volumes:
  mysql:
  static:
  media: