FROM nginx:1.19-alpine

# Remove the default nginx configuration file
RUN rm -rf /etc/nginx/conf.d/*
RUN rm /etc/nginx/nginx.conf

# Copy your custom, full configuration file into the container
COPY mysite.conf /etc/nginx/nginx.conf

EXPOSE 80